export const circuitos2025 = [ // Es muy posible que algunos nombres cambien o no coincidan y por eso no se muestren
    "Albert Park Circuit",
    "Shanghai International Circuit",
    "Suzuka International Racing Course",
    "Bahrain International Circuit",
    "Jeddah Corniche Circuit",
    "Miami International Autodrome",
    "Autodromo Enzo e Dino Ferrari",
    "Circuit de Monaco",
    "Circuit de Barcelona-Catalunya",
    "Circuit Gilles-Villeneuve",
    "Red Bull Ring",
    "Silverstone Circuit",
    "Spa-Francorchamps",
    "Hungaroring",
    "Zandvoort",
    "Autodromo Nazionale Monza",
    "Baku City Circuit",
    "Marina Bay Street Circuit",
    "Circuit of the Americas",
    "Autodromo Hermanos Rodriguez",
    "Autodromo Jose Carlos Pace",
    "Las Vegas Strip Circuit",
    "Lusail International Circuit",
    "Yas Marina Circuit"
];